// Complete South African provinces and cities/towns data
export const southAfricanLocations = {
  "Western Cape": [
    "Cape Town",
    "Stellenbosch",
    "Paarl",
    "Worcester",
    "George",
    "Mossel Bay",
    "Hermanus",
    "Swellendam",
    "Oudtshoorn",
    "Knysna",
    "Plettenberg Bay",
    "Caledon",
    "Robertson",
    "Montagu",
    "Beaufort West",
    "Vredenburg",
    "Saldanha",
    "Malmesbury",
    "Wellington",
    "Grabouw",
    "Ceres",
    "Tulbagh",
    "Bredasdorp",
    "Riversdale",
    "Ladismith",
  ],
  Gauteng: [
    "Johannesburg",
    "Pretoria",
    "Soweto",
    "Sandton",
    "Randburg",
    "Roodepoort",
    "Germiston",
    "Benoni",
    "Boksburg",
    "Kempton Park",
    "Alberton",
    "Springs",
    "Edenvale",
    "Midrand",
    "Centurion",
    "Vanderbijlpark",
    "Vereeniging",
    "Krugersdorp",
    "Randfontein",
    "Westonaria",
    "Carletonville",
    "Bronkhorstspruit",
    "Nigel",
    "Heidelberg",
    "Magaliesburg",
  ],
  "KwaZulu-Natal": [
    "Durban",
    "Pietermaritzburg",
    "Newcastle",
    "Richards Bay",
    "Ladysmith",
    "Empangeni",
    "Pinetown",
    "Chatsworth",
    "Umlazi",
    "Phoenix",
    "Westville",
    "Kloof",
    "Hillcrest",
    "Ballito",
    "Umhlanga",
    "Scottburgh",
    "Port Shepstone",
    "Kokstad",
    "Dundee",
    "Vryheid",
    "Estcourt",
    "Howick",
    "Margate",
    "Amanzimtoti",
    "Stanger",
  ],
  "Eastern Cape": [
    "Port Elizabeth",
    "East London",
    "Uitenhage",
    "King William's Town",
    "Grahamstown",
    "Queenstown",
    "Mdantsane",
    "Bhisho",
    "Alice",
    "Fort Beaufort",
    "Cradock",
    "Graaff-Reinet",
    "Mthatha",
    "Butterworth",
    "Jeffreys Bay",
    "Somerset East",
    "Humansdorp",
    "Kirkwood",
    "Jansenville",
    "Steytlerville",
    "Willowmore",
    "Pearston",
    "Bedford",
    "Adelaide",
    "Cathcart",
  ],
  "Free State": [
    "Bloemfontein",
    "Welkom",
    "Kroonstad",
    "Bethlehem",
    "Sasolburg",
    "Phuthaditjhaba",
    "Virginia",
    "Odendaalsrus",
    "Parys",
    "Ficksburg",
    "Harrismith",
    "Heilbron",
    "Hoopstad",
    "Bothaville",
    "Vredefort",
    "Frankfort",
    "Reitz",
    "Senekal",
    "Winburg",
    "Boshof",
    "Dealesville",
    "Theunissen",
    "Brandfort",
    "Petrusburg",
    "Koffiefontein",
  ],
  Limpopo: [
    "Polokwane",
    "Tzaneen",
    "Thohoyandou",
    "Phalaborwa",
    "Louis Trichardt",
    "Mokopane",
    "Musina",
    "Giyani",
    "Lebowakgomo",
    "Bela-Bela",
    "Modimolle",
    "Thabazimbi",
    "Lephalale",
    "Marble Hall",
    "Hoedspruit",
    "Burgersfort",
    "Dendron",
    "Ellisras",
    "Naboomspruit",
    "Nylstroom",
    "Potgietersrus",
    "Warmbaths",
    "Bandelierkop",
    "Chuniespoort",
    "Duiwelskloof",
  ],
  Mpumalanga: [
    "Nelspruit",
    "Witbank",
    "Secunda",
    "Standerton",
    "Middelburg",
    "Ermelo",
    "Piet Retief",
    "Barberton",
    "White River",
    "Sabie",
    "Graskop",
    "Lydenburg",
    "Belfast",
    "Carolina",
    "Volksrust",
    "Hazyview",
    "Komatipoort",
    "Malelane",
    "Pilgrim's Rest",
    "Dullstroom",
    "Waterval Boven",
    "Machadodorp",
    "Badplaas",
    "Bethal",
    "Delmas",
  ],
  "North West": [
    "Rustenburg",
    "Klerksdorp",
    "Potchefstroom",
    "Mahikeng",
    "Brits",
    "Vryburg",
    "Stilfontein",
    "Orkney",
    "Hartbeespoort",
    "Zeerust",
    "Lichtenburg",
    "Schweizer-Reneke",
    "Taung",
    "Mmabatho",
    "Wolmaransstad",
    "Koster",
    "Swartruggens",
    "Groot Marico",
    "Sannieshof",
    "Delareyville",
    "Coligny",
    "Christiana",
    "Bloemhof",
    "Ganyesa",
    "Tosca",
  ],
  "Northern Cape": [
    "Kimberley",
    "Upington",
    "Kuruman",
    "Springbok",
    "De Aar",
    "Postmasburg",
    "Kathu",
    "Calvinia",
    "Carnarvon",
    "Colesberg",
    "Hanover",
    "Hopetown",
    "Noupoort",
    "Prieska",
    "Victoria West",
    "Britstown",
    "Richmond",
    "Fraserburg",
    "Sutherland",
    "Williston",
    "Loxton",
    "Beaufort West",
    "Murraysburg",
    "Griekwastad",
    "Douglas",
  ],
} as const

export type Province = keyof typeof southAfricanLocations
export type City = (typeof southAfricanLocations)[Province][number]

// Helper functions
export const getProvinces = (): Province[] => {
  return Object.keys(southAfricanLocations) as Province[]
}

export const getCitiesForProvince = (province: Province): string[] => {
  return southAfricanLocations[province] || []
}
